# Generated by Django 5.0.4 on 2025-01-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicCarry', '0011_address_alter_payment_order_payment_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='CCV',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('Amex', 'Amex')], max_length=50, null=True),
        ),
    ]
