# Generated by Django 5.0.4 on 2025-01-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicCarry', '0012_remove_payment_transaction_id_payment_ccv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='CCV',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
