# Generated by Django 5.0.4 on 2025-01-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicCarry', '0014_alter_payment_order_alter_payment_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
