# Generated by Django 5.0.4 on 2025-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicCarry', '0017_remove_cart_is_ordered_cart_status_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ORDERED', 'Ordered'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
