# Generated by Django 5.0.4 on 2025-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicCarry', '0018_cart_updated_at_alter_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Ordered', 'Ordered')], default='Active', max_length=20),
        ),
    ]
